#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

timezone="$(timedatectl show --value --property=Timezone)"
key=$(ynh_string_random --length=64)

ynh_app_setting_set --key=php_upload_max_filesize --value=5G
ynh_app_setting_set --key=php_post_max_size --value=5G

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Download, check integrity, uncompress and patch the source from manifest.toml
ynh_setup_source --dest_dir="$install_dir"

chown -R $app:www-data $data_dir/uploads $data_dir/users $data_dir/metadata
chmod -R 775 $data_dir/uploads $data_dir/users $data_dir/metadata

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add --template="config.php" --destination="$install_dir/config/config.php"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create a PHP-FPM config (with conf/extra_php-fpm.conf being appended to it)
ynh_config_add_phpfpm

# Create a dedicated NGINX config using the conf/nginx.conf template
ynh_config_add_nginx

#=================================================
# INSTALL FILERISE WITH COMPOSER
#=================================================
ynh_script_progression "Installing $app with Composer..."

ynh_composer_exec install --no-dev

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
